// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/COMA-tor/rtm/rest/models"
)

// GetAirportIATATypeLastOKCode is the HTTP code returned for type GetAirportIATATypeLastOK
const GetAirportIATATypeLastOKCode int = 200

/*GetAirportIATATypeLastOK Returns the latest measurement of the given type from the given airport

swagger:response getAirportIATATypeLastOK
*/
type GetAirportIATATypeLastOK struct {

	/*
	  In: Body
	*/
	Payload *models.Measure `json:"body,omitempty"`
}

// NewGetAirportIATATypeLastOK creates GetAirportIATATypeLastOK with default headers values
func NewGetAirportIATATypeLastOK() *GetAirportIATATypeLastOK {

	return &GetAirportIATATypeLastOK{}
}

// WithPayload adds the payload to the get airport i a t a type last o k response
func (o *GetAirportIATATypeLastOK) WithPayload(payload *models.Measure) *GetAirportIATATypeLastOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get airport i a t a type last o k response
func (o *GetAirportIATATypeLastOK) SetPayload(payload *models.Measure) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAirportIATATypeLastOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
