// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetAirportIATATypeParams creates a new GetAirportIATATypeParams object
// no default values defined in spec.
func NewGetAirportIATATypeParams() GetAirportIATATypeParams {

	return GetAirportIATATypeParams{}
}

// GetAirportIATATypeParams contains all the bound params for the get airport i a t a type operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetAirportIATAType
type GetAirportIATATypeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	IATA string
	/*
	  Required: true
	  In: path
	*/
	Type string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAirportIATATypeParams() beforehand.
func (o *GetAirportIATATypeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rIATA, rhkIATA, _ := route.Params.GetOK("IATA")
	if err := o.bindIATA(rIATA, rhkIATA, route.Formats); err != nil {
		res = append(res, err)
	}

	rType, rhkType, _ := route.Params.GetOK("type")
	if err := o.bindType(rType, rhkType, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIATA binds and validates parameter IATA from path.
func (o *GetAirportIATATypeParams) bindIATA(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.IATA = raw

	return nil
}

// bindType binds and validates parameter Type from path.
func (o *GetAirportIATATypeParams) bindType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Type = raw

	return nil
}
