// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAirportIATAOKCode is the HTTP code returned for type GetAirportIATAOK
const GetAirportIATAOKCode int = 200

/*GetAirportIATAOK Returns the latest measurement for each type from the given airport

swagger:response getAirportIATAOK
*/
type GetAirportIATAOK struct {

	/*
	  In: Body
	*/
	Payload *GetAirportIATAOKBody `json:"body,omitempty"`
}

// NewGetAirportIATAOK creates GetAirportIATAOK with default headers values
func NewGetAirportIATAOK() *GetAirportIATAOK {

	return &GetAirportIATAOK{}
}

// WithPayload adds the payload to the get airport i a t a o k response
func (o *GetAirportIATAOK) WithPayload(payload *GetAirportIATAOKBody) *GetAirportIATAOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get airport i a t a o k response
func (o *GetAirportIATAOK) SetPayload(payload *GetAirportIATAOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAirportIATAOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
