// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/COMA-tor/rtm/rest/models"
)

// GetAirportIATATypeOKCode is the HTTP code returned for type GetAirportIATATypeOK
const GetAirportIATATypeOKCode int = 200

/*GetAirportIATATypeOK Returns the latest measurement of the given type from the given airport

swagger:response getAirportIATATypeOK
*/
type GetAirportIATATypeOK struct {

	/*
	  In: Body
	*/
	Payload *models.Measure `json:"body,omitempty"`
}

// NewGetAirportIATATypeOK creates GetAirportIATATypeOK with default headers values
func NewGetAirportIATATypeOK() *GetAirportIATATypeOK {

	return &GetAirportIATATypeOK{}
}

// WithPayload adds the payload to the get airport i a t a type o k response
func (o *GetAirportIATATypeOK) WithPayload(payload *models.Measure) *GetAirportIATATypeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get airport i a t a type o k response
func (o *GetAirportIATATypeOK) SetPayload(payload *models.Measure) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAirportIATATypeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
