// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Airport sensor measurements
//
//  A REST api used to get filtered measurements from airport sensors.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
