// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A REST api used to get filtered measurements from airport sensors.",
    "title": "Airport sensor measurements",
    "version": "1.0.0"
  },
  "paths": {
    "/airport/{IATA}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "IATA",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the latest measurement for each type from the given airport",
            "schema": {
              "type": "object",
              "required": [
                "temperature",
                "pressure",
                "wind_speed"
              ],
              "properties": {
                "pressure": {
                  "$ref": "#/definitions/measure"
                },
                "temperature": {
                  "$ref": "#/definitions/measure"
                },
                "windspeed": {
                  "$ref": "#/definitions/measure"
                }
              }
            }
          }
        }
      }
    },
    "/airport/{IATA}/{type}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "IATA",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "type",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "default": 50,
            "description": "Number of measures to return",
            "name": "count",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 1000,
            "description": "Time step between measures for aggregation in ms",
            "name": "step",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns an array of the latest measurements of the given type from the given airport",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/measure"
              }
            }
          }
        }
      }
    },
    "/airport/{IATA}/{type}/last": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "IATA",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "type",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the latest measurement of the given type from the given airport",
            "schema": {
              "$ref": "#/definitions/measure"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "measure": {
      "type": "object",
      "required": [
        "timestamp",
        "value",
        "unit"
      ],
      "properties": {
        "timestamp": {
          "type": "integer"
        },
        "unit": {
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A REST api used to get filtered measurements from airport sensors.",
    "title": "Airport sensor measurements",
    "version": "1.0.0"
  },
  "paths": {
    "/airport/{IATA}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "IATA",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the latest measurement for each type from the given airport",
            "schema": {
              "type": "object",
              "required": [
                "temperature",
                "pressure",
                "wind_speed"
              ],
              "properties": {
                "pressure": {
                  "$ref": "#/definitions/measure"
                },
                "temperature": {
                  "$ref": "#/definitions/measure"
                },
                "windspeed": {
                  "$ref": "#/definitions/measure"
                }
              }
            }
          }
        }
      }
    },
    "/airport/{IATA}/{type}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "IATA",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "type",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "default": 50,
            "description": "Number of measures to return",
            "name": "count",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 1000,
            "description": "Time step between measures for aggregation in ms",
            "name": "step",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns an array of the latest measurements of the given type from the given airport",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/measure"
              }
            }
          }
        }
      }
    },
    "/airport/{IATA}/{type}/last": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "IATA",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "type",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the latest measurement of the given type from the given airport",
            "schema": {
              "$ref": "#/definitions/measure"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "measure": {
      "type": "object",
      "required": [
        "timestamp",
        "value",
        "unit"
      ],
      "properties": {
        "timestamp": {
          "type": "integer"
        },
        "unit": {
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      }
    }
  }
}`))
}
